title: Resume
description: |
  個人事業主(フリーランス)として活動中のkat0です。
  システム開発、業務委託(準委任契約)などご相談は
  以下「お問い合わせ」ボタン先よりご連絡下さい。
contact:
  name: お問い合わせ
  link: "comming soom..."
sns:
  - name: Twitter
    link: https://twitter.com/hd2g2g
  - name: Wantedly
    link: https://www.wantedly.com/id/hd2g_kat0
  - name: GitHub
    link: https://github.com/hd2g
