open Tyxml
open Elem

let sns_icons_of_config (config : Config.t) =
  config.sns
  |> List.map (fun { Config.Other_site.name; link } ->
       match List.assoc_opt name Icons.as_acons with
       | Some icon ->
         Elem.a_blank ~attrs:[ Html.a_href link; Html.a_class [ "link" ] ] [ icon ]
       | None ->
         Elem.a_blank
           ~attrs:[ Html.a_href link; Html.a_class [ "link" ] ]
           [ Html.txt name ])

let render (config : Config.t) =
  Html.(
    footer
      ~a:
        [ a_class
            [ "footer"
            ; "bottom-0"
            ; "items-center"
            ; "p-12"
            ; "text-base-content"
            ; "bg-base-300"
            ]
        ]
      [ div
          ~a:[ a_class [ "items-center"; "grid-flow-row" ] ]
          [ p
              [ txt (config.title ^ " site is maintenanced in ")
              ; a_blank
                  ~attrs:[ a_class [ "link" ]; a_href "https://github.com/hd2g/kat0" ]
                  [ txt config.title ]
              ; txt "."
              ]
          ; p
              [ txt "This website was generated by "
              ; a_blank
                  ~attrs:[ a_class [ "link" ]; a_href "https://pages.github.com/" ]
                  [ txt "GitHub Pages" ]
              ; txt "."
              ]
          ]
      ; div ~a:[ a_class [ "grid-flow-col"; "gap-4" ] ] (sns_icons_of_config config)
      ])
